---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: heading
  label: Content
- type: document
  path: config.toml
  label: home
- type: directory
  path: data
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: heading
  label: Items
- type: directory
  path: content/network
  label: Network items
  create: all
  match: "**/*"
- type: directory
  path: content/news_events
  label: News events items
  create: all
  match: "**/*"
- type: directory
  path: content/newsletters
  label: Newsletters items
  create: all
  match: "**/*"
- type: directory
  path: content/teams
  label: Teams items
  create: all
- type: directory
  path: content/ddb
  label: Dorset Deserves Better
- type: directory
  path: content/hedge
  label: The Great Hedgerow
  create: all
  match: "**/*"
- type: heading
  label: SEO
- type: directory
  path: content/about
  label: About SEO
  create: all
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact SEO
  create: all
  match: "**/*"
- type: directory
  path: content/donate
  label: Donate SEO
  create: all
  match: "**/*"
- type: directory
  path: content/join
  label: Join SEO
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
